### ISSUE TITLE
Error when loading TJCompressor

### ISSUE THREAD

**Issue by vincentneo** [Sergey-Terekhin/libjpeg-turbo-net#2]
`System.DllNotFoundException: 'Unable to load DLL 'turbojpeg': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'
`
At line `TJCompressor compressor = new TJCompressor();`

Why is this so, and how do I resolve this?

**Comment by Sergey-Terekhin** [comment]
Hi!
You need to use package `libjpeg-turbo-native-win` for windows (currently it is only supported) or manually copy `turbojpeg.dll` in the output folder
Then, before any use of wrapper call static method `TJInitializer.Initialize();`

**Comment by vincentneo** [comment]
Ok, thank you!

**Comment by mwiegant** [comment]
Would it be possible to update the README for this project to reflect that this library requires installation of libjpeg-turbo-native-win for windows?

**Comment by Sergey-Terekhin** [comment]
Done :)
