### ISSUE TITLE
nuget package does not contain native assemblies

### ISSUE THREAD

**Issue by hillin** [Sergey-Terekhin/libjpeg-turbo-net#3]
The current nuget package (v 2.0.15) does not contain native turbojpeg.dll assemblies.

**Comment by Sergey-Terekhin** [comment]
yes, you need to use package libjpeg-turbo-native-win - it contains binaries for windows platform

**Comment by hillin** [comment]
Great, thanks!

**Comment by hillin** [comment]
@Sergey-Terekhin I came across this issue again, could you be more specific on how the package `libjpeg-turbo-native-win` should be used?
I have a test project that:
- is targeted to .netcoreapp3.1
- references both `libjpeg-turbo-net` and `libjpeg-turbo-native-win`, version 2.0.15
- tries to encode an image with libjpeg-turbo-net
and it fails looking for the turbojpeg.dll:

> System.DllNotFoundException: 'Unable to load DLL 'turbojpeg' or one of its dependencies: The specified module could not be found. (0x8007007E)'

**Comment by Sergey-Terekhin** [comment]
I'm not sure if it works under net core - never checked it. I think it would be better to download the latest build from https://github.com/libjpeg-turbo/libjpeg-turbo/releases and add libraries directly to your project

Unfortunately, I don't have time to adopt package for net core, sorry
