### ISSUE TITLE
AccessViolationException occurs when reusing a TJCompressor

### ISSUE THREAD

**Issue by hillin** [Sergey-Terekhin/libjpeg-turbo-net#4]
If a `TJCompressor` is reused (i.e. compress multiple images with the same `TJCompressor` object), `AccessViolationException` may randomly occur in the native code. However, creating `TJCompressor` objects for each image will have no problem.

I reckon this could be a thread-safety issue. Is `TJCompressor` thread safe?

**Comment by Sergey-Terekhin** [comment]
No, TJCompressor is not thread-safe, you need to use pool or synchronize access to it

**Comment by hillin** [comment]
Thanks, that explains the issue.
