### ISSUE TITLE
Installing package in Visual Studio 2015

### ISSUE THREAD

**Issue by inbinary** [Sergey-Terekhin/libjpeg-turbo-net#5]
Hey, excuse me for being a noob, but I'm having trouble getting this installed correctly.

Just to be sure, if I'm installing this on a .net application using vs2015, I only need to add the nuget package libjpeg-turbo-native-win and nothing else? The application I'm installing this on currently uses the old libjpeg code and it's quite slow.

The issue I'm running into is that after I install the package, the turbojpeg.dll isn't being added and it throws a com error when I try to add it manually. 

Any ideas? thanks!!

-Ryan

**Comment by Sergey-Terekhin** [comment]
Hi!
I don't now what is broken in VS2015 - possible some issue in old nuget. Adding reference to `libjpeg-turbo-native-win` should be enough to get native library
As workaround you can add it manually to the project from official repo: https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/2.0.2
 
Best regards!

**Comment by inbinary** [comment]
Thanks. I finally got it working a while back so I'm closing this out.
