### ISSUE TITLE
A few examples to go back to managed code?

### ISSUE THREAD

**Issue by tonyp7** [Sergey-Terekhin/libjpeg-turbo-net#6]
Hello Sergey,

Good lib, but not very user friendly. You should add an example to convert back to managed code; for isntance to load an image:

```csharp
TJDecompressor decompressor = new TJDecompressor();
byte[] data = System.IO.File.ReadAllBytes(pathToJPEGImage);
var result = decompressor.Decompress(data, TJPixelFormats.TJPF_BGR, TJFlags.NONE);
IntPtr dataPtr = CopyDataToPointer(result.Data);
var bmp = new Bitmap(result.Width, result.Height, result.RowBytes, System.Drawing.Imaging.PixelFormat.Format24bppRgb, dataPtr);
```

On my machine I got the following results loading a big 10 mb JPEG

ImageMagick.NET Q8 x64: 602 ms
Microsoft JPEG (Image lib): 878 ms
Turbo JPEG: 537 ms

... So definitely the fastest!

**Comment by Sergey-Terekhin** [comment]
Thank you for the feedback!
In the next release I will add some pieces of documentation
